### ISSUE TITLE
Diamond nugget ore dictionary name

### ISSUE THREAD

**Issue by tgstyle** [Chicken-Bones/Translocators#16]
Shouldn't it be nuggetDiamond and not diamondNugget?

**Comment by Chicken-Bones** [comment]
maybe it should, does it matter? feel free to submit a PR

**Comment by tgstyle** [comment]
I would say it may matter only because the standard formatting seems to be nuggetType. This is the only one in my modpack that is the opposite =). I can submit a PR when I have time to figure it out.

**Comment by joserobjr** [comment]
It was fixed on this commit: https://github.com/Chicken-Bones/Translocators/commit/e936b4994a3a7148d44f609d4ad2157f02d9c4c2
